# Generated by Django 3.0.2 on 2020-02-02 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sembadaapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sembadaapi',
            options={'managed': False},
        ),
    ]
